@echo off
echo Starting Web Server...
start "" "build\Release\WebServerApp.exe"

echo Waiting for server to initialize...
timeout /t 2 > nul

echo Starting Locust...
start cmd /k "python -m locust -f locustfile.py"

echo Waiting for Locust to start...
timeout /t 2 > nul

echo Opening Locust UI in browser...
start http://localhost:8089
